import './globals.css'
import Image from 'next/image'
import logo from '../../public/images/hero_Logo.svg'
import fundo from '../../public/images/hero_Image.svg'
import Header from "@/components/Header"
import { lazy, Suspense } from 'react'

export const metadata = {
  title: 'Valor de uma vida',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>

        <Header />

        <div className='w-full h-[688px] flex items-center relative box-border '>

          <Image className=' h-full object-cover absolute top-0 left-0'
            src={fundo}
            alt='Fundo estatico da pagina'
          />

          <div className='w-full h-[100%] flex items-center relative box-border pl-[25.45px] pr-[25.45px] background-Fundo'>

            <div className='flex items-center '>
              <Image className='w-[135px] h-[135px]' src={logo} alt='Logo valor de uma vida' />
              <h2 className='ml-[20px] font-bold font-sans uppercase ext-[28px] text-white text-shadow'>valor de uma vida</h2>
            </div>

            <div className='w-[48%] h-[100%]  absolute right-0  bg-layoutClipPath box-shadow-custom custom-clip-path'>

              <div className='w-full h-full relative'>

                <h1 className='max-w-[517px] text-shadow absolute right-[25px] top-[43%] text-[21px] uppercase leading-[27px] text-white font-sans font-bold text-end whitespace-wrap'>
                  desde 2014 prestando auxílio <br /> a pessoas com <strong className='text-yellow-300'> Vulnerabilidades sociais</strong> e portadoras de diversas <strong className='text-yellow-300'>doenças crônicas</strong> Em <strong>várzea Paulista</strong>
                </h1>

              </div>

            </div>

          </div>

        </div>

        {children}

      </body>
    </html>
  )
}
