import './globals.css'
import Header from "@/components/Header"

export const metadata = {
  title: 'Valor de uma vida',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Header />

        {children}
        
      </body>
    </html>
  )
}
